/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankTransfer {
  'bankAccountNumber' : string,
  'routingNumber' : string,
  'bankName' : string,
  'transactionId' : string,
}
export interface CryptoWallet {
  'cryptoType' : string,
  'transactionHash' : string,
  'walletAddress' : string,
}
export interface MobilePayment {
  'provider' : string,
  'mobileNumber' : string,
  'transactionId' : string,
}
export interface Payment {
  'id' : string,
  'status' : string,
  'driverId' : string,
  'paymentMethod' : string,
  'commissionFee' : number,
  'timestamp' : Timestamp,
  'amount' : number,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addPayment' : ActorMethod<[string, Payment], undefined>,
  'addTransfer' : ActorMethod<[string, string, string], undefined>,
  'calculateCommission' : ActorMethod<[number, number], number>,
  'getAllCompleteTransfers' : ActorMethod<[], Array<Payment>>,
  /**
   * / Function to retrieve all payment transactions
   */
  'getAllTransactions' : ActorMethod<[], Array<Payment>>,
  /**
   * / Function to view application statistics
   */
  'getAppStats' : ActorMethod<
    [],
    {
      'totalCommissions' : number,
      'totalPayments' : bigint,
      'totalAmount' : number,
    }
  >,
  /**
   * / Function to get the total payout amount for a driver
   */
  'getDriverPayoutAmount' : ActorMethod<[string], number>,
  /**
   * / Function to get a driver's transaction history
   */
  'getDriverTransactionHistory' : ActorMethod<[string], Array<Payment>>,
  'getPayment' : ActorMethod<[string], Payment>,
  'getPaymentStatus' : ActorMethod<[string], string>,
  'initiateBankTransfer' : ActorMethod<[string, BankTransfer], BankTransfer>,
  'initiateCryptoTransfer' : ActorMethod<[string, CryptoWallet], CryptoWallet>,
  'initiateMobilePayment' : ActorMethod<[string, MobilePayment], MobilePayment>,
  'processPayment' : ActorMethod<
    [string, number, string, number],
    { 'paymentId' : string, 'payment' : Payment }
  >,
  'viewPayment' : ActorMethod<[string], Payment>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];