/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'driverId' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'commissionFee' : IDL.Float64,
  'timestamp' : Timestamp,
  'amount' : IDL.Float64,
});
export const BankTransfer = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'routingNumber' : IDL.Text,
  'bankName' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const CryptoWallet = IDL.Record({
  'cryptoType' : IDL.Text,
  'transactionHash' : IDL.Text,
  'walletAddress' : IDL.Text,
});
export const MobilePayment = IDL.Record({
  'provider' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'transactionId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPayment' : IDL.Func([IDL.Text, Payment], [], ['oneway']),
  'addTransfer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'calculateCommission' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Float64],
      [],
    ),
  'getAllCompleteTransfers' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAppStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCommissions' : IDL.Float64,
          'totalPayments' : IDL.Int,
          'totalAmount' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getDriverPayoutAmount' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getDriverTransactionHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPayment' : IDL.Func([IDL.Text], [Payment], ['query']),
  'getPaymentStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'initiateBankTransfer' : IDL.Func(
      [IDL.Text, BankTransfer],
      [BankTransfer],
      [],
    ),
  'initiateCryptoTransfer' : IDL.Func(
      [IDL.Text, CryptoWallet],
      [CryptoWallet],
      [],
    ),
  'initiateMobilePayment' : IDL.Func(
      [IDL.Text, MobilePayment],
      [MobilePayment],
      [],
    ),
  'processPayment' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
      [IDL.Record({ 'paymentId' : IDL.Text, 'payment' : Payment })],
      [],
    ),
  'viewPayment' : IDL.Func([IDL.Text], [Payment], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'driverId' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'commissionFee' : IDL.Float64,
    'timestamp' : Timestamp,
    'amount' : IDL.Float64,
  });
  const BankTransfer = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'routingNumber' : IDL.Text,
    'bankName' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const CryptoWallet = IDL.Record({
    'cryptoType' : IDL.Text,
    'transactionHash' : IDL.Text,
    'walletAddress' : IDL.Text,
  });
  const MobilePayment = IDL.Record({
    'provider' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  
  return IDL.Service({
    'addPayment' : IDL.Func([IDL.Text, Payment], [], ['oneway']),
    'addTransfer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'calculateCommission' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'getAllCompleteTransfers' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAppStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCommissions' : IDL.Float64,
            'totalPayments' : IDL.Int,
            'totalAmount' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getDriverPayoutAmount' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getDriverTransactionHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPayment' : IDL.Func([IDL.Text], [Payment], ['query']),
    'getPaymentStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'initiateBankTransfer' : IDL.Func(
        [IDL.Text, BankTransfer],
        [BankTransfer],
        [],
      ),
    'initiateCryptoTransfer' : IDL.Func(
        [IDL.Text, CryptoWallet],
        [CryptoWallet],
        [],
      ),
    'initiateMobilePayment' : IDL.Func(
        [IDL.Text, MobilePayment],
        [MobilePayment],
        [],
      ),
    'processPayment' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
        [IDL.Record({ 'paymentId' : IDL.Text, 'payment' : Payment })],
        [],
      ),
    'viewPayment' : IDL.Func([IDL.Text], [Payment], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };